#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

case `uname` in
	Darwin)
		export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home
		if which docker-machine >/dev/null 2>&1; then
			eval $(docker-machine env docker-vm)
		fi
		;;
esac

export VISUAL=/usr/bin/vim
export EDITOR=/usr/bin/vim

